### ISSUE TITLE
SpaceRepository.AddGate(string connectionstring) causes console app to never terminate

### ISSUE THREAD

**Issue by UndyingJellyfish** [pSpaces/dotSpace#10]
I'm not exactly sure about the terminology, but basically, the gate you add is never and can never be closed, meaning that the program is forever stuck in an un-interactable state after the Main method has terminated. For a proper example of this, please see the attached file. Simply comment and uncomment the marked line to see an illustration of the gate-problem.

What I'd suggest is to either implement a de-register-gate method of some sort, so that the program may actually close when the Main is done. Maybe it would even be better to have RepositoryBase also implement IDisposable, for a more formal way of disposing of an object after use. This would also allow for the pattern of 
`using (var repo = new SpaceRepository(){
    // ...
}`

[SpaceRepoIssue.txt](https://github.com/pSpaces/dotSpace/files/1609060/SpaceRepoIssue.txt)

**Comment by sequenze** [comment]
Yes you are right. When a Gate is added, the SpaceRepository begins to listen immediately thereafter. Functionality to break this cycle has not been implemented.
Thank you for the feedback.

**To sum up:** features to close both the individual gates, as well as the entire SpaceRepository would be necessary features.

**Comment by albertolluch** [comment]
I agree with @sequenze: methods for removing/closing gates and repositories are necessary. Some of them are actually specified in the guidelines but still need to be implemented.

**Comment by sequenze** [comment]
Version 1.0.8 has now been published as both a nuget and on git, with features allowing gates to be closed.
