### ISSUE TITLE
Hello World in C#

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/dotSpace#5]
I think this issue

https://github.com/pSpaces/Programming-with-Spaces/issues/7

fits better here :)

**Comment by sequenze** [comment]
Helloworld added to dotSpace. This will be moved to its seperate repo along with all other example projects once the repo has been created.

**Comment by albertolluch** [comment]
thanks @sequenze. There is a little discrepancy: space `dtu` should be called `inbox`.
